### ISSUE TITLE
Cloning and building fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by koushik-ms** [marcodiiga/filepie#2]
When I tried the steps in the README on a fresh installation of Ubuntu, the repo failed to clone (due to SSH authentication) initially. Changing the git URL to HTTPS solved that problem. 

However the project did not build due to 2 reasons:
1. cmake build fails with `Error: Could not load cache`. Upon an initial clone, user needs to run `cmake .` on project folder to setup all the project files. See [this](https://stackoverflow.com/a/38889442/450836) SO answer for details.
2. cmake build fails again with below error 
```
/home/user/src/filepie/filepie.cpp: In function ‘void scan_path(std::__cxx11::string, std::vector<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, long unsigned int, bool, float> >&, std::unordered_map<std::__cxx11::basic_string<char>, long unsigned int>&)’:
/home/user/src/filepie/filepie.cpp:169:45: error: ‘accumulate’ is not a member of ‘std’
   const std::size_t total_files_size = std::accumulate(files.begin(), files.end(), std::size_t(0), [](std::size_t a, const auto& b) {
                                             ^~~~~~~~~~
make[2]: *** [CMakeFiles/filepie.dir/build.make:63: CMakeFiles/filepie.dir/filepie.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/filepie.dir/all] Error 2
```
The reason for cloning the repo is to only use the tool, not necessarily for further development.

**Comment by koushik-ms** [comment]
Created pull request #3  with proposed solution. Request to review and merge.

**Comment by marcodiiga** [comment]
Thanks for fixing this! Merged
